### ISSUE TITLE
Custom Path Kubelet: CSI Pods are stuck in ContainerCreating Phase with error MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry is not a directory

### ISSUE THREAD

**Issue by rpanduranga** [vmware-tanzu/vsphere-kubernetes-drivers-operator#103]
**Issue/Feature Description:**
Custom Path Kubelet: CSI Pods are stuck in ContainerCreating Phase with error 
MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry is not a directory

**What type of Issue/Feature is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
 /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**Why this fix/ feature is needed(give scenarios or use cases):**
On custom K8 deployments on VMWARE, a different kubelet path is used other than the default /var/lib/kubelet but /var/data/kubelet instead. As a resullt, the default value is passed to the csi node driver to be used to mount the storage /var/lib/kubelet fails to perform the mounts
 
**How to reproduce, in case of a bug:**
Configure a K8 cluster with a different kublet path other than /var/lib/kubelet

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
On editing the CSI DaemonSet manually, there are other kubelet path that needs updation

1.
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --health-port=9809
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/csi.vsphere.vmware.com/csi.sock          <-------------- Path needs update

2.
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry          <------------- Path needs update
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi.vsphere.vmware.com         <------------- Path needs update
          type: DirectoryOrCreate

Search the Daemonset output for /var and /var/lib needs to be replaced with the custom path

**Comment by ridaz** [comment]
Closing the issue since code changes have been merged to the main branch.
Reference PR: https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pull/113
