### ISSUE TITLE
csi-node daemonset pods need to run with an SCC of privileged on Openshift

### ISSUE THREAD

**Issue by tejohnson123** [vmware-tanzu/vsphere-kubernetes-drivers-operator#132]
**Issue/Feature Description:**
When installing the CSI driver on openshift using the VDO, it does not set the csi-node service account to run the pods as privileged.  
**What type of Issue/Feature is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
/kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**Why this fix/ feature is needed(give scenarios or use cases):**
Privileged is needed by the CSI-Node so that it can access the host paths and perform disk operations on the VM.  I was able to get it to run by running the following command:
`oc -n vmware-system-csi adm policy add-scc-to-user privileged -z vsphere-csi-node`
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
In our installation of openshift on the IBM Satellite on VMware, the default SCC is restricted.  This prevents csi-node daemonset pods from running.

**Comment by jvrahav** [comment]
Hi @tejohnson123 ,

we have this in our documentation https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/blob/main/docs/getting-started/getting-started-from-operator-hub.md#pre-requisites

do you think this would suffice

**Comment by ridaz** [comment]
Hi,
Closing the issue since `installing the CSI driver on Openshift using the VDO, it does not set the csi-node service account to run the pods as privileged` have been documented in the getting started guide as pre-requisites.
