### ISSUE TITLE
vdoctl update compatibility-matrix panics

### ISSUE THREAD

**Issue by Bhagyashreek8** [vmware-tanzu/vsphere-kubernetes-drivers-operator#144]
**Issue/Feature Description:**
`vdoctl update compatibility-matrix` command panics with `invalid memory address or nil pointer dereference`

```
vdoctl update compatibility-matrix <file_path>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x214fa3b]

goroutine 1 [running]:
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.updateMatrix({0xc0001f7a10, 0x0, 0x0})
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/update_matrix.go:75 +0x2fb
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.glob..func6(0x3714b60, {0xc0001f7a10, 0x1, 0x1})
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/update_matrix.go:45 +0x45
github.com/spf13/cobra.(*Command).execute(0x3714b60, {0xc0001f79b0, 0x1, 0x1})
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x3715560)
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.Execute()
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/root.go:65 +0x25
main.main()
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/main.go:31 +0x71
```

**What type of Issue/Feature is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**Why this fix/ feature is needed(give scenarios or use cases):**
Not able to update compatibility matrix per custom vSphere CSI.

**How to reproduce, in case of a bug:**
Run `vdoctl update compatibility-matrix` command

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by Bhagyashreek8** [comment]
Installed vdoctl v0.2.0 from - https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases
`[vdoctl-mac.tar.gz](https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.2.0/vdoctl-mac.tar.gz)`

**Comment by Bhagyashreek8** [comment]
The command panics with custom compatibility.yaml from local path and also the github path
```
% vdoctl update compatibility-matrix https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/compatibility.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x214fa3b]

goroutine 1 [running]:
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.updateMatrix({0xc00007f4d0, 0x0, 0x0})
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/update_matrix.go:75 +0x2fb
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.glob..func6(0x3714b60, {0xc00007f4d0, 0x1, 0x1})
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/update_matrix.go:45 +0x45
github.com/spf13/cobra.(*Command).execute(0x3714b60, {0xc00007f4a0, 0x1, 0x1})
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x3715560)
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/smohammadasi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd.Execute()
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/cmd/root.go:65 +0x25
main.main()
	/Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/vdoctl/main.go:31 +0x71
```

**Comment by asifdxtreme** [comment]
Thanks @Bhagyashreek8 for reporting this bug, it will be of great help if you can provide us some more information on the env :
  - Do you have existing volumes attached to any pods?
  - Output of `vdoctl version`
  - Output of `kubectl get pv` , `kubectl get pvc`

**Comment by Bhagyashreek8** [comment]
Hi @asifdxtreme Thanks for the quick response.
We dont have existing volumes attached to any pods

```
% vdoctl version
kubernetes Version : 1.20
VDO Version        : d89d95ff753569a866af9c7f4d8f1029dd3d5bdb88af0fb1ee2a8e324020a383
vSphere Versions   : [7.0.2]
CSI Version        : 2.4.0
CPI Version        : Not Configured
```

```
% kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                           STORAGECLASS           REASON   AGE
pvc-9e6bd646-552f-4296-a784-b9fd56dad8e9   5Gi        RWO            Delete           Released   default/example-raw-block-pvc   example-raw-block-sc            8d
```

```
kubectl get pvc
No resources found in default namespace.
```

Now, i deleted the PV and tried to update compatibility matrix, still the same error. 
Am I missing something @asifdxtreme

**Comment by Bhagyashreek8** [comment]
@asifdxtreme Any inputs on the above issue will be very much helpful.

**Comment by asifdxtreme** [comment]
Thanks @Bhagyashreek8 for the input, as I see there are some PV's available in your env.
CSI has some manual pre-requisite which needs to be followed before performing CSI upgrade, you can find more details about this over here https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-3F277B52-68CC-4125-AD0F-E7293940B4B4.html

**Comment by asifdxtreme** [comment]
You need to clear/remount  the PV before upgrade, let us know if you still face the same problem @Bhagyashreek8

**Comment by ridaz** [comment]
Closing the bug since it doesn't have any updates from last 15 days.
Please open a new bug if you still face similar issues.
