### ISSUE TITLE
VDO deployment in OCP 4.8.2 - one or more requirements couldn't be found

### ISSUE THREAD

**Issue by erezbatish** [vmware-tanzu/vsphere-kubernetes-drivers-operator#146]
Hi
I'm trying to deploy VDO 0.1.5 on OCP 4.8.2 single node (lab environment), I followed all the prereq from the getting started guide CSI driver, however the operator deployment is in status Pending with event error - one or more requirements couldn't be found.
Any idea what is wrong or how can I get more details on which requirement is missing?
Thanks

**Comment by saintdle** [comment]
4.8 is not supported currently.

**Comment by erezbatish** [comment]
Which versions are supported?
Is there another way to install the vSphere CSI in OCP 4.8?

**Comment by asifdxtreme** [comment]
@erezbatish The new version of operator 0.2.0 is available now in catalog, please use the new version to deploy vdo in OCP 4.8

**Comment by asifdxtreme** [comment]
This issue has been resolved with the latest version of vdo in redhat catalog, please free to reopen this If issue persist
