### ISSUE TITLE
New version of VDO operator to be compatible with vsphere-csi-driver:2.5.0

### ISSUE THREAD

**Issue by gauravAggrahari** [vmware-tanzu/vsphere-kubernetes-drivers-operator#149]
Hi Team,
The new version(2.5.0) of the `vsphere-csi-driver` is available. Is there an expected date of the operator release which will be compatible with `vsphere-csi-driver:2.5.0`?

**Comment by jvrahav** [comment]
https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/tag/0.3.0 support csi 2.5.1

**Comment by asifdxtreme** [comment]
This issue is fixed, going ahead to close it.
