### ISSUE TITLE
IBM vsphere-csi-driver template requires a refresh to support the ROKS 4.13 onwards

### ISSUE THREAD

**Issue by gauravAggrahari** [vmware-tanzu/vsphere-kubernetes-drivers-operator#187]
Hi,
Currently we have vsphere-csi-driver:2.7.0 template in IBM which does have support only till ROKS 4.12. 
The template needs to be refreshed to support ROKS 4.13 and above. 

The 2.7.0 compatibility has max version supported as k8s 1.25

**Comment by gauravAggrahari** [comment]
https://github.com/IBM/ibm-satellite-storage/issues/406

**Comment by asifdxtreme** [comment]
Support for CSI 3.0.0 added https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/pull/189
