### ISSUE TITLE
versionConfigContent not getting updated.

### ISSUE THREAD

**Issue by asifdxtreme** [vmware-tanzu/vsphere-kubernetes-drivers-operator#48]
**Issue/Feature Description:**
VersionConfigContent is not getting updated by `vdoctl configure compat` command using Local filePath

**What type of Issue/Feature is this?**
 /kind bug

**Why this fix/ feature is needed(give scenarios or use cases):**
This fix is required to update the content of compatibility matrix by using LocaFilePath

**How to reproduce, in case of a bug:**
```
smohammadasi@smohammadas-a01 github-action % vdoctl configure compat
✔ Local filepath
Local filepath file:///Users/smohammadasi/go/src/github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/hack/github-action/comp-matrix.yaml
smohammadasi@smohammadas-a01 github-action % kubectl describe configmaps -n vmware-system-vdo compat-matrix-config
Name:         compat-matrix-config
Namespace:    vmware-system-vdo
Labels:       <none>
Annotations:  <none>

Data
====
auto-upgrade:
----
disabled
versionConfigURL:
----
https://testfly.com
Events:  <none>

```

**Comment by aggarwalta** [comment]
Currently, updating ConfigMap or any other resource is not supported in the flow. 
One modification for this is we can check ConfigMap existence after the user executes the command **_vdoctl configure compat_**. If the configmap already exists, we can throw an error. Please let me know if we should apply the same for other resources like secret and vsphereCloudConfigs as well. cc @jvrahav @asifdxtreme

**Comment by jvrahav** [comment]
> Currently, updating ConfigMap or any other resource is not supported in the flow.
> One modification for this is we can check ConfigMap existence after the user executes the command **_vdoctl configure compat_**. If the configmap already exists, we can throw an error. Please let me know if we should apply the same for other resources like secret and vsphereCloudConfigs as well. cc @jvrahav @asifdxtreme

1. we should follow the desired state model at all places.
2. all commands should be idempotent

considering the above two points, we should be ensuring that any update operation is allowed.
If the configmap already exists we should compare the content of the desired config(from command) and state of config(from k8s cluster) . if there is a difference then we need to update the config to reach the desired config as requested by the user. This should apply for both file as well http url's
